---
micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  io:
    watch:
      paths: src/main/kotlin
      restart: true

---
datasources:
  default:
    url: jdbc:mariadb://localhost/wxdemo?characterEncoding=utf8&useSSL=false
    driverClassName: org.mariadb.jdbc.Driver
    username: demo
    password: 12345678
    schema-generate: CREATE_DROP
    dialect: MYSQL

wx:
  mp:
    configs:
      - appId: XXX #微信appId 各位大哥记得自行设置!!!
        secret: XXX
        token:
        AESkey:
  pay:
    appId: XXX
    mchId: XXX
    mchKey: XXX #微信支付商户密钥
    keyPath: XXX.p12  # p12证书的位置

---
jackson:
  json-view:
    enabled: true
